name: Deploy

on:
  push:
    branches: [main, dev, test]
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy-to-cloudflare:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.run-build.outputs.artefactname }}
      - name: ⚠ Prepare assets ⚠
        run: rm ./index.html
      - name: Publish only assets to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_DEPLOY_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_DEPLOY_PAGES_ACCOUNT_ID }}
          projectName: axa-performance-report
          branch: ${{ needs.run-build.outputs.branch }}
          directory: ./
